name: Newman Run
on: [push]
                
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: postman/newman
    steps:
      - uses: actions/checkout@v1
      - name: Run API Tests
        run: newman run https://www.getpostman.com/collections/56ac0f8216f6ad711d27   
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2.4.2
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
