name: Newman Run
on: [push]

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          apiKey: $16957912-074e606e-5fee-45f1-b802-a11ff6de17fd
          collection: https://www.getpostman.com/collections/56ac0f8216f6ad711d27
          environment: https://www.getpostman.com/collections/56ac0f8216f6ad711d27
      - name: Run Test 
        run: newman run https://www.getpostman.com/collections/56ac0f8216f6ad711d27   
