name: Newman Run
on: [push]
                
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: postman/newman
    steps:
      - uses: actions/checkout@v1
      - name: Run API Tests
        run: newman run https://www.getpostman.com/collections/56ac0f8216f6ad711d27   
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-results/**/*.xml
